# ONLY LOWERCASE
services:
  idcleaner:
    build: .
    container_name: idcleaner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/app/data
      - records:/app/records
    labels:
      - "homepage.group=Products"
      - "homepage.name=idcleaner"
      - "homepage.icon=si-python"
      - "homepage.description=Fixing your gmail"
      - "homepage.server=my-docker"
      - "homepage.widget.type=docker"
      - "homepage.widget.container=idcleaner"

volumes:
  data:
  records:
